# Generated by Django 5.1.4 on 2025-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menucategory_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_file',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_menus/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
