# Generated by Django 5.1.4 on 2025-04-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='image_cover',
        ),
    ]
