# Generated by Django 5.1.4 on 2025-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_rename_image_restaurant_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='terrace',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
