# Generated by Django 5.1.4 on 2025-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_terrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slogan',
            field=models.CharField(blank=True, default='Address Of Taste', max_length=255, null=True),
        ),
    ]
