# Generated by Django 5.1.4 on 2025-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='no_of_seats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
