# Generated by Django 5.1.4 on 2025-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_no_of_seats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
