# Generated by Django 5.1.4 on 2025-06-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_options_restaurant_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('general_pdf', models.FileField(blank=True, null=True, upload_to='menus/general/')),
                ('breakfast_pdf', models.FileField(blank=True, null=True, upload_to='menus/breakfast/')),
                ('lunch_pdf', models.FileField(blank=True, null=True, upload_to='menus/lunch/')),
                ('dinner_pdf', models.FileField(blank=True, null=True, upload_to='menus/dinner/')),
                ('beverage_pdf', models.FileField(blank=True, null=True, upload_to='menus/beverage/')),
                ('offers_pdf', models.FileField(blank=True, null=True, upload_to='menus/offers/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.restaurant')),
            ],
        ),
    ]
