# Generated by Django 5.1.4 on 2025-04-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('meeting_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_room',
            field=models.ForeignKey(blank=True, help_text='Select the room where the event will take place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='meeting_rooms.meetingroom'),
        ),
    ]
