# Generated by Django 5.1.4 on 2025-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hotels', '0006_remove_facility_hotel_remove_feature_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='hotel',
        ),
        migrations.AddField(
            model_name='faq',
            name='hotels',
            field=models.ManyToManyField(related_name='faqs', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='hotels',
            field=models.ManyToManyField(related_name='subscribers', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hotels',
            field=models.ManyToManyField(related_name='privacy_policies', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='hotels',
            field=models.ManyToManyField(related_name='terms_and_conditions', to='hotels.hotel'),
        ),
    ]
