# Generated by Django 5.1.4 on 2025-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_faq_hotel_remove_newsletter_hotel_and_more"),
        ("hotels", "0008_hotelservice_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hotel_articles/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotels",
                    models.ManyToManyField(related_name="articles", to="hotels.hotel"),
                ),
            ],
            options={
                "verbose_name": "Hotel Article",
                "verbose_name_plural": "Hotel Articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotels",
                    models.ManyToManyField(related_name="sitemaps", to="hotels.hotel"),
                ),
            ],
            options={
                "verbose_name": "Sitemap",
                "verbose_name_plural": "Sitemaps",
                "ordering": ["-created_at"],
            },
        ),
    ]
