# Generated by Django 5.1.4 on 2025-04-24 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotelarticle_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelarticle',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelarticle',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotelarticle',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotelarticle',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
