# Generated by Django 5.1.4 on 2025-05-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
        ('hotels', '0065_alter_hotel_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_description', models.TextField(blank=True, null=True)),
                ('partner_image', models.ImageField(blank=True, null=True, upload_to='partners')),
                ('partner_url', models.URLField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Partnership Corporates',
            },
        ),
    ]
