# Generated by Django 5.1.4 on 2025-05-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_partner"),
        ("hotels", "0069_hotel_image_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                (
                    "job_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Separate each requirement with a line break",
                        null=True,
                    ),
                ),
                (
                    "job_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career",
                "verbose_name_plural": "Careers",
                "ordering": ["-created_at"],
            },
        ),
    ]
