# Generated by Django 5.1.4 on 2025-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_career"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
