# Generated by Django 5.1.4 on 2025-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_careerapplication'),
        ('hotels', '0092_alter_hotelservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('training', 'Training')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('hotel', 'slug')},
        ),
    ]
