# Generated by Django 5.1.4 on 2025-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_career_job_type_alter_career_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_description',
            field=models.TextField(max_length=70),
        ),
    ]
