# Generated by Django 5.1.4 on 2025-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting_rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingroom",
            name="area",
            field=models.FloatField(default=30, help_text="Area in square meters"),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of people the room can accommodate.",
                null=True,
            ),
        ),
    ]
