# Generated by Django 5.1.4 on 2025-05-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0002_meetingroom_area_alter_meetingroom_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meeting_room_seating_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='meetingroom',
            old_name='image',
            new_name='image_cover',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='can_have_weeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='wedding_brochure',
            field=models.FileField(blank=True, null=True, upload_to='wedding_brochures/'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='area',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='meeting_rooms', to='meeting_rooms.meetingroomamenity'),
        ),
        migrations.CreateModel(
            name='MeetingRoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meeting_room_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meeting_rooms.meetingroom')),
            ],
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='seating_arrangements',
            field=models.ManyToManyField(blank=True, related_name='meeting_rooms', to='meeting_rooms.seatingarrangement'),
        ),
    ]
