# Generated by Django 5.1.4 on 2025-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0003_meetingroomamenity_seatingarrangement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingroomamenity',
            options={'verbose_name': 'Meeting Room Amenity', 'verbose_name_plural': 'Meeting Room Amenities'},
        ),
        migrations.AlterModelOptions(
            name='meetingroomimages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meeting Room Image', 'verbose_name_plural': 'Meeting Room Images'},
        ),
        migrations.AlterModelOptions(
            name='seatingarrangement',
            options={'verbose_name': 'Seating Arrangement', 'verbose_name_plural': 'Seating Arrangements'},
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='area',
            field=models.FloatField(blank=True, default=30, help_text='Area in square meters', null=True),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
