# Generated by Django 5.1.4 on 2025-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0005_alter_meetingroom_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
