# Generated by Django 5.1.4 on 2025-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0006_meetingroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
