# Generated by Django 5.1.4 on 2025-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0008_alter_meetingroom_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('corporate_pdf', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('wedding_pdf', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('bofeh_pdf', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('setmenu_pdf', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('offers_pdf', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
