# Generated by Django 5.1.4 on 2025-06-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0090_alter_hotel_contact_banner_and_more'),
        ('meeting_rooms', '0009_eventbrochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrochure',
            name='hotel',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='event_brochures', to='hotels.hotel'),
            preserve_default=False,
        ),
    ]
