# Generated by Django 5.1.4 on 2025-06-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0010_eventbrochure_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingroom',
            old_name='can_have_weeding',
            new_name='can_host_wedding',
        ),
    ]
