# Generated by Django 5.1.4 on 2025-04-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='hotel_covers/')),
                ('fact_sheet', models.FileField(blank=True, null=True, upload_to='hotel_fact_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gym', 'Gym'), ('spa', 'Spa'), ('clinic', 'Clinic'), ('pool', 'Swimming Pool'), ('bar', 'Bar / Lounge'), ('restaurant', 'Restaurant'), ('kids_play_area', "Kids' Play Area"), ('game_room', 'Game Room'), ('cinema', 'Cinema Room'), ('golf', 'Golf Course'), ('water_sports', 'Water Sports Center'), ('business_center', 'Business Center'), ('coworking', 'Co-working Space'), ('event_hall', 'Event Hall'), ('concierge', 'Concierge'), ('shuttle', 'Shuttle Service'), ('laundry', 'Laundry Service'), ('atm', 'ATM'), ('currency_exchange', 'Currency Exchange'), ('gift_shop', 'Gift Shop'), ('salon', 'Hair / Beauty Salon')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('number_of_beds', models.PositiveIntegerField(default=1)),
                ('area', models.FloatField(help_text='Area in square meters')),
                ('is_suit', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='room_covers/')),
                ('check_in_notes', models.TextField(blank=True)),
                ('check_out_notes', models.TextField(blank=True)),
                ('special_check_in_instructions', models.TextField(blank=True)),
                ('children_and_extra_beds_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='feature_icons/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='specification_icons/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='hotels.room')),
            ],
        ),
    ]
