# Generated by Django 5.1.4 on 2025-04-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessage',
            name='description',
            field=models.TextField(default='Welcome to our hotel.'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcome_messages', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='welcome_messages/'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='welcomemessage',
            name='message',
            field=models.TextField(default='We’re happy to have you with us.'),
        ),
    ]
