# Generated by Django 5.1.4 on 2025-04-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_welcomemessage_description_welcomemessage_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomemessage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_messages', to='hotels.hotel'),
        ),
    ]
