# Generated by Django 5.1.4 on 2025-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_alter_welcomemessage_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="amenity_icons/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="hotels.amenity"
            ),
        ),
    ]
