# Generated by Django 5.1.4 on 2025-04-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_amenity_description_alter_amenity_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='room',
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.facility'),
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotels.feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='hotels.amenity'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
