# Generated by Django 5.1.4 on 2025-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_remove_facility_hotel_remove_feature_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="slogan",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
