# Generated by Django 5.1.4 on 2025-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0008_hotelservice_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="icon",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
