# Generated by Django 5.1.4 on 2025-04-24 12:13

import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_hotel_city_hotel_country_hotel_email_hotel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=hotels.models.rename_uploaded_image),
        ),
    ]
