# Generated by Django 5.1.4 on 2025-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='includes_breakfast',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
