# Generated by Django 5.1.4 on 2025-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_alter_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(blank=True, help_text='Area in square meters'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
