# Generated by Django 5.1.4 on 2025-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_alter_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('gym', 'Fitness Center'), ('spa', 'Spa'), ('clinic', 'Clinic'), ('pool', 'Swimming Pool'), ('bar', 'Bar / Lounge'), ('kids_play_area', "Kids' Play Area"), ('game_room', 'Game Room'), ('cinema', 'Cinema Room'), ('golf', 'Golf Course'), ('water_sports', 'Water Sports Center'), ('business_center', 'Business Center'), ('coworking', 'Co-working Space'), ('event_hall', 'Event Hall'), ('concierge', 'Concierge'), ('shuttle', 'Shuttle Service'), ('laundry', 'Laundry Service'), ('atm', 'ATM'), ('currency_exchange', 'Currency Exchange'), ('gift_shop', 'Gift Shop'), ('salon', 'Hair / Beauty Salon')], max_length=50),
        ),
    ]
