# Generated by Django 5.1.4 on 2025-04-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0017_alter_facility_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"ordering": ["type", "name"], "verbose_name_plural": "Facilities"},
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="facilities",
        ),
        migrations.AddField(
            model_name="facility",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilities",
                to="hotels.hotel",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="facility",
            unique_together={("hotel", "name")},
        ),
    ]
