# Generated by Django 5.1.4 on 2025-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0018_alter_facility_options_remove_hotel_facilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
