# Generated by Django 5.1.4 on 2025-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0019_facility_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="detail_file",
            field=models.FileField(blank=True, null=True, upload_to="facility_files/"),
        ),
        migrations.AddField(
            model_name="facility",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
