# Generated by Django 5.1.4 on 2025-04-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0020_facility_detail_file_facility_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="facility_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.facility",
                    ),
                ),
            ],
        ),
    ]
