# Generated by Django 5.1.4 on 2025-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0021_facilityimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="review_images/"),
        ),
        migrations.AddField(
            model_name="review",
            name="view_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
