# Generated by Django 5.1.4 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0023_hotelservice_icon_alter_hotelservice_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelservice",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hotelservice",
            name="pricing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per_night", "Per Night"),
                    ("daily", "Daily"),
                    ("once", "One Time"),
                ],
                default="per_night",
                max_length=20,
                null=True,
            ),
        ),
    ]
