# Generated by Django 5.1.4 on 2025-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0024_alter_hotelservice_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelservice",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
