# Generated by Django 5.1.4 on 2025-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0025_hotelservice_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelservice",
            name="price_currency",
            field=models.CharField(
                blank=True,
                choices=[("USD", "USD"), ("EGP", "EGP")],
                default="EGP",
                max_length=3,
                null=True,
            ),
        ),
    ]
