# Generated by Django 5.1.4 on 2025-04-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0026_hotelservice_price_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelservice",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=8, null=True
            ),
        ),
    ]
