# Generated by Django 5.1.4 on 2025-04-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0027_alter_hotelservice_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelservice",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Dimension Must be : 375x500px. JPEG or PNG format.",
                null=True,
                upload_to="hotel_services/",
            ),
        ),
    ]
