# Generated by Django 5.1.4 on 2025-04-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0028_alter_hotelservice_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("tripadvisor", "TripAdvisor"),
                            ("website", "Official Website"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("pinterest", "Pinterest"),
                            ("snapchat", "Snapchat"),
                            ("reddit", "Reddit"),
                            ("tumblr", "Tumblr"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
    ]
