# Generated by Django 5.1.4 on 2025-04-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0030_imagecover_delete_hotelservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image_cover',
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hotel_services/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricing_type', models.CharField(choices=[('per_night', 'Per Night'), ('daily', 'Daily'), ('once', 'One Time')], default='per_night', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', to='hotels.hotel')),
            ],
        ),
    ]
