# Generated by Django 5.1.4 on 2025-04-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0031_remove_hotel_image_cover_hotelservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='price_currency',
            field=models.CharField(default='EGP', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
