# Generated by Django 5.1.4 on 2025-04-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0032_hotelservice_featured_hotelservice_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Dimension: 375x500', null=True, upload_to='hotel_services/'),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EGP', 'EGP')], default='EGP', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('per_night', 'Per Night'), ('daily', 'Daily'), ('once', 'One Time')], default='per_night', max_length=20, null=True),
        ),
    ]
