# Generated by Django 5.1.4 on 2025-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0033_alter_hotelservice_image_alter_hotelservice_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelservice',
            options={'verbose_name': 'Hotel Service', 'verbose_name_plural': 'Hotel Services'},
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
