# Generated by Django 5.1.4 on 2025-04-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0034_alter_hotelservice_options_hotelservice_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('hotel_main', 'Hotel Main Page'), ('offers', 'Offers Page'), ('rooms', 'Rooms Page'), ('facilities', 'Facilities Page'), ('events', 'Events Page'), ('restaurant', 'Restaurant Page'), ('spa', 'Spa Page'), ('gym', 'Gym Page')], max_length=50)),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_backgrounds', to='hotels.hotel')),
            ],
        ),
    ]
