# Generated by Django 5.1.4 on 2025-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0035_pagebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
