# Generated by Django 5.1.4 on 2025-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0036_room_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_of_persons',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
