# Generated by Django 5.1.4 on 2025-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_room_number_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number_of_persons',
            field=models.CharField(blank=True, default='1-2', max_length=50, null=True),
        ),
    ]
