# Generated by Django 5.1.4 on 2025-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_alter_room_number_of_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Bed'), ('sofa', 'Sofa Bed')], default='twin', max_length=20),
        ),
    ]
