# Generated by Django 5.1.4 on 2025-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_room_bed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(blank=True, help_text='Area in square meters', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
