# Generated by Django 5.1.4 on 2025-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0040_alter_room_area_alter_room_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotels.amenity'),
        ),
    ]
