# Generated by Django 5.1.4 on 2025-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0041_room_short_description_room_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in_notes',
            field=models.TextField(blank=True, default='Check-in from 9:00 AM - anytime'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out_notes',
            field=models.TextField(blank=True, default='Check-out before 12:00 PM'),
        ),
    ]
