# Generated by Django 5.1.4 on 2025-04-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0043_hotelpagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelVideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('rooms', 'Rooms Page'), ('restaurants', 'Restaurants Page'), ('offers', 'Offers Page'), ('spa', 'Spa Page'), ('meetings', 'Meetings Page'), ('events', 'Events Page'), ('gallery', 'Gallery Page'), ('contact', 'Contact Page')], max_length=100)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='hotel_video_banners/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_banners', to='hotels.hotel')),
            ],
            options={
                'ordering': ['page'],
                'unique_together': {('hotel', 'page')},
            },
        ),
    ]
