# Generated by Django 5.1.4 on 2025-04-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0044_hotelvideobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='short_description_1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='short_description_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='short_description_3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
