# Generated by Django 5.1.4 on 2025-04-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0045_facility_short_description_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='short_description_1',
            new_name='short_note_1',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='short_description_2',
            new_name='short_note_2',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='short_description_3',
            new_name='short_note_3',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='notes',
        ),
    ]
