# Generated by Django 5.1.4 on 2025-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0046_rename_short_description_1_facility_short_note_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
