# Generated by Django 5.1.4 on 2025-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0047_facility_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Activating this makes the facility appear in the page'),
        ),
    ]
