# Generated by Django 5.1.4 on 2025-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0048_facility_icon_alter_facility_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='image',
            new_name='description_image',
        ),
        migrations.AddField(
            model_name='facility',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='facility_images/'),
        ),
    ]
