# Generated by Django 5.1.4 on 2025-05-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0049_rename_image_facility_description_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='description_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='cover_image',
        ),
    ]
