# Generated by Django 5.1.4 on 2025-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0050_rename_description_image_facility_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityimage',
            name='image',
            field=models.ImageField(help_text='Dimension: 375x500 - This Image Will Be Shown Down in The Facility Page', upload_to='facility_images/'),
        ),
    ]
