# Generated by Django 5.1.4 on 2025-05-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0051_alter_facilityimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name': "Room's Amenity", 'verbose_name_plural': 'Room Amenities'},
        ),
        migrations.AlterModelOptions(
            name='hotelservice',
            options={'verbose_name': 'Hotel Service ( Hotel Amenities )', 'verbose_name_plural': 'Hotel Services ( Hotel Amenities )'},
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this service from frontend'),
        ),
    ]
