# Generated by Django 5.1.4 on 2025-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0053_alter_facility_slug_alter_hotel_slug_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='featured',
            field=models.BooleanField(default=False, help_text='Activating this makes the service appear in (Pricing Section ) Please no more than 3 services'),
        ),
    ]
