# Generated by Django 5.1.4 on 2025-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0055_alter_hotelservice_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('Per Night', 'Per Night'), ('Daily', 'Daily'), ('Once', 'One Time')], default='Per Night', max_length=20, null=True),
        ),
    ]
