# Generated by Django 5.1.4 on 2025-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0059_alter_offer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='booking_link',
            field=models.URLField(blank=True, help_text='Link to booking page or external site', null=True),
        ),
    ]
