# Generated by Django 5.1.4 on 2025-05-04 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0061_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
