# Generated by Django 5.1.4 on 2025-05-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0062_alter_galleryitem_options_galleryitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact_banner',
            field=models.ImageField(blank=True, help_text=' For Contact Page', null=True, upload_to='contact_banners/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_image1',
            field=models.ImageField(blank=True, help_text=' For Contact Page', null=True, upload_to='contact_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_image2',
            field=models.ImageField(blank=True, help_text=' For Contact Page', null=True, upload_to='contact_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text=' For Contact Page', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
