# Generated by Django 5.1.4 on 2025-05-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0063_hotel_contact_banner_hotel_contact_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text=' For Contact Page', max_length=1500, null=True),
        ),
    ]
