# Generated by Django 5.1.4 on 2025-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0064_alter_hotel_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='map_embed_url',
            field=models.CharField(blank=True, help_text=' For Contact Page', max_length=1500, null=True),
        ),
    ]
