# Generated by Django 5.1.4 on 2025-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0065_alter_hotel_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_views',
            field=models.CharField(choices=[('sea', 'Sea View'), ('city', 'City View'), ('garden', 'Garden View'), ('pool', 'Pool View'), ('mountain', 'Mountain View')], default='sea', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('king/twin', 'King / Twin Bed'), ('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Bed'), ('sofa', 'Sofa Bed')], default='twin', max_length=20),
        ),
    ]
