# Generated by Django 5.1.4 on 2025-05-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0066_room_room_views_alter_room_bed_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in_notes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out_notes',
        ),
        migrations.AddField(
            model_name='room',
            name='room_features_section_1',
            field=models.TextField(blank=True, default='Modified_Room Featured Section (Nourhan)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_features_section_2',
            field=models.TextField(blank=True, default='Modified_Room Featured Section 2 (Nourhan)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_features_section_3',
            field=models.TextField(blank=True, default='Modified_Room Featured Section 3 (Nourhan)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('king/twin', 'King / Twin Bed'), ('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Bed'), ('sofa', 'Sofa Bed')], default='king/twin', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_views',
            field=models.CharField(choices=[('sea', 'Sea View'), ('city', 'City View'), ('garden', 'Garden View'), ('pool', 'Pool View'), ('mountain', 'Mountain View')], default='city', max_length=20),
        ),
    ]
