# Generated by Django 5.1.4 on 2025-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0068_alter_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_cover',
            field=models.ImageField(blank=True, help_text='Signature image for carousel and listings', null=True, upload_to='hotel_covers/'),
        ),
    ]
