# Generated by Django 5.1.4 on 2025-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0069_hotel_image_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelpagebanner",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home Page"),
                    ("rooms", "Rooms Page"),
                    ("dining", "Dining Page"),
                    ("offers", "Offers Page"),
                    ("services", "Services Page"),
                    ("meeting", "Meeting Page"),
                    ("wedding", "Wedding Page"),
                    ("images", "Images Page"),
                    ("video", "Videos Page"),
                    ("about", "About Page"),
                    ("faqs", "Faqs Page"),
                    ("team", "Team Page"),
                    ("careers", "Careers Page"),
                    ("events", "Events Page"),
                    ("contact", "Contact Page"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="hotelvideobanner",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home Page"),
                    ("rooms", "Rooms Page"),
                    ("dining", "Dining Page"),
                    ("offers", "Offers Page"),
                    ("services", "Services Page"),
                    ("meeting", "Meeting Page"),
                    ("wedding", "Wedding Page"),
                    ("images", "Images Page"),
                    ("video", "Videos Page"),
                    ("about", "About Page"),
                    ("faqs", "Faqs Page"),
                    ("team", "Team Page"),
                    ("careers", "Careers Page"),
                    ("events", "Events Page"),
                    ("contact", "Contact Page"),
                ],
                max_length=100,
            ),
        ),
    ]
