# Generated by Django 5.1.4 on 2025-05-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0070_alter_hotelpagebanner_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='synxis_hotel_id',
            field=models.CharField(blank=True, help_text='The hotel ID used by SynXis booking engine', max_length=20, null=True),
        ),
    ]
