# Generated by Django 5.1.4 on 2025-05-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0071_hotel_synxis_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo for the hotel', null=True, upload_to='hotel_logos/'),
        ),
    ]
