# Generated by Django 5.1.4 on 2025-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0072_hotel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
