# Generated by Django 5.1.4 on 2025-05-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0073_hotelimage_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='icon',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
