# Generated by Django 5.1.4 on 2025-05-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0076_welcomemessage_location_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoverSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoverImageTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hover_tabs/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='hotels.hoversection')),
            ],
        ),
    ]
