# Generated by Django 5.1.4 on 2025-05-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0077_hoversection_hoverimagetab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoverimagetab',
            options={'ordering': ['id']},
        ),
    ]
