# Generated by Django 5.1.4 on 2025-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0078_alter_hoverimagetab_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='synxis_chain_id',
            field=models.CharField(blank=True, help_text='The chain ID used by SynXis booking engine', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hoversection',
            name='name',
            field=models.CharField(help_text='Must Be slug of the hotel or page', max_length=100, unique=True),
        ),
    ]
