# Generated by Django 5.1.4 on 2025-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0079_hotel_synxis_chain_id_alter_hoversection_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image',
            new_name='image_cover',
        ),
        migrations.AddField(
            model_name='offer',
            name='image_card',
            field=models.ImageField(blank=True, help_text='Dimension: 375x500 & Showing only in cards and not offer main page', null=True, upload_to='offer_cards/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Activating this makes the offer appear in the Offer Main page'),
        ),
    ]
