# Generated by Django 5.1.4 on 2025-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0080_rename_image_offer_image_cover_offer_image_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_card',
            field=models.BooleanField(default=False, help_text='Activating this makes the offer appear in the Offer Card section'),
        ),
    ]
