# Generated by Django 5.1.4 on 2025-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0081_offer_is_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
