# Generated by Django 5.1.4 on 2025-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0082_alter_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvideobanner',
            name='video_image_cover',
            field=models.ImageField(blank=True, help_text='Dimension: 1920x1080', null=True, upload_to='hotel_video_banners/'),
        ),
    ]
