# Generated by Django 5.1.4 on 2025-06-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0085_room_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['display_order']},
        ),
    ]
