# Generated by Django 5.1.4 on 2025-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0086_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description for search engines (max 160 characters).', max_length=160),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search relevance.', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (max 70 characters). Defaults to hotel name if empty.', max_length=70),
        ),
    ]
