# Generated by Django 5.1.4 on 2025-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0087_hotel_meta_description_hotel_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='virtual_tour_link',
            field=models.URLField(blank=True, help_text='Link to a virtual tour of the room', null=True),
        ),
    ]
