# Generated by Django 5.1.4 on 2025-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0089_alter_hotel_contact_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact_banner',
            field=models.ImageField(blank=True, help_text=' For Contact Page', null=True, upload_to='contact_banners/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_image1',
            field=models.ImageField(blank=True, help_text=' For Contact Page', null=True, upload_to='contact_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_image2',
            field=models.ImageField(blank=True, help_text=' For Contact Page', null=True, upload_to='contact_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='map_embed_url',
            field=models.CharField(blank=True, help_text=' For Contact Page', max_length=1500, null=True),
        ),
    ]
