# Generated by Django 5.1.4 on 2025-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0090_alter_hotel_contact_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
