# Generated by Django 5.1.4 on 2025-06-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0091_alter_hotelservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='description',
            field=models.TextField(blank=True, help_text='beware of services height in hotel home page !!!', null=True),
        ),
    ]
