# Generated by Django 5.1.4 on 2025-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0092_alter_hotelservice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file for the home page', null=True, upload_to='home_videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for the home page video', null=True)),
                ('why_triumph_banner', models.ImageField(blank=True, help_text="Image for the 'Why Triumph' section", null=True, upload_to='home_banners/')),
                ('why_triumph_title', models.CharField(blank=True, help_text="Title for the 'Why Triumph' section", max_length=255, null=True)),
                ('why_triumph_video_url', models.URLField(blank=True, help_text="YouTube or Vimeo URL for the 'Why Triumph' video", null=True)),
                ('why_triumph_video_banner', models.ImageField(blank=True, help_text="Image for the 'Why Triumph' video section", null=True, upload_to='home_banners/')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='why_triumph_description',
            field=models.TextField(blank=True, help_text="Description for the 'Why Triumph' section of the facility"),
        ),
    ]
