# Generated by Django 5.1.4 on 2025-06-18 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0093_homepagedata_facility_why_triumph_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagedata',
            options={'verbose_name': 'Home Page Data', 'verbose_name_plural': 'Home Page Data'},
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file for the home page', null=True, upload_to='home_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube or Vimeo URL for the home page video'),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='why_triumph_title',
            field=models.CharField(blank=True, default='', help_text="Title for the 'Why Triumph' section", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='why_triumph_video_url',
            field=models.URLField(blank=True, default='', help_text="YouTube or Vimeo URL for the 'Why Triumph' video"),
        ),
    ]
