# Generated by Django 5.1.4 on 2025-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0094_alter_homepagedata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='why_triumph_description',
        ),
        migrations.AddField(
            model_name='hotel',
            name='why_triumph_description',
            field=models.TextField(blank=True, help_text="Description for the 'Why Triumph' section of the facility"),
        ),
    ]
