# Generated by Django 5.1.4 on 2025-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0095_remove_facility_why_triumph_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_banner',
            field=models.ImageField(blank=True, help_text='Dimension: 375x500', null=True, upload_to='review_banners/'),
        ),
    ]
