# Generated by Django 5.1.4 on 2025-06-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0096_review_review_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_banner',
        ),
    ]
