# Generated by Django 5.1.4 on 2025-06-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0097_remove_review_review_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedata',
            name='review_banner',
            field=models.ImageField(blank=True, help_text='Image for the home page review section', null=True, upload_to='home_banners/'),
        ),
    ]
