# Generated by Django 5.1.4 on 2025-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0098_homepagedata_review_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='page',
            field=models.CharField(choices=[('hotel_main', 'Hotel Main Page')], max_length=50),
        ),
    ]
