# Generated by Django 5.1.4 on 2025-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0099_alter_pagebackground_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='children_and_extra_beds_notes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_features_section_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_features_section_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_features_section_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='special_check_in_instructions',
        ),
        migrations.AddField(
            model_name='room',
            name='room_policy_section_1',
            field=models.TextField(blank=True, default='Modified_Room policy Section 1 (Nourhan)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_policy_section_2',
            field=models.TextField(blank=True, default='Modified_Room policy Section 2 (Nourhan)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_policy_section_3',
            field=models.TextField(blank=True, default='Modified_Room policy Section 3 (Nourhan)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_policy_section_4',
            field=models.TextField(blank=True, default='Modified_Room policy Section 4 (Nourhan)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_policy_section_5',
            field=models.TextField(blank=True, default='Modified_Room policy Section 5 (Nourhan)'),
        ),
    ]
